# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-02 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_resev_end', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_id_room', to='reservation.Room'),
        ),
        migrations.AddField(
            model_name='bookingrooms',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.Booking'),
        ),
        migrations.AddField(
            model_name='bookingrooms',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.Room'),
        ),
        migrations.AddField(
            model_name='booking',
            name='reservation',
            field=models.ManyToManyField(through='reservation.BookingRooms', to='reservation.Room'),
        ),
    ]
